libalpm: more verbose error message for unsatisfied deps before: $ sudo pacman -S kdebase :: kdebase-3.5.0-4: local version is up to date. Upgrade anyway? [Y/n] resolving dependencies... done. looking for inter-conflicts... error: failed to prepare transaction (could not satisfy dependencies)
after:
$ sudo pacman -S kdebase
:: kdebase-3.5.0-4: local version is up to date. Upgrade anyway? [Y/n]
resolving dependencies... done.
looking for inter-conflicts...
ERROR: cannot satisfy dependency for "kdebase" (requires "hal>=0.5.5-2")
error: failed to prepare transaction (could not satisfy dependencies)