libalpm: more verbose error messages on file conflicts currently: $ sudo pacman -S foomatic-filters-ppds --noconfirm resolving dependencies... done. looking for inter-conflicts... done.
Targets: foomatic-filters-ppds-20051211-1

Total Package Size:   11.5 MB

Beginning upgrade process...

checking package integrity... done.
ERROR: could not prepare transaction
error: failed to commit transaction (unexpected error)

expected:
$ sudo pacman -S foomatic-filters-ppds --noconfirm
resolving dependencies... done.
looking for inter-conflicts... done.

Targets: foomatic-filters-ppds-20051211-1

Total Package Size:   11.5 MB

Beginning upgrade process...

checking package integrity... done.
ERROR: foomatic-filters-ppds: /usr/share/ppd: exists in filesystem
ERROR: could not prepare transaction
error: failed to commit transaction (conflicting files)