check if enough free space if available
example:
$ sudo pacman -S openoffice.org
looking for inter-conflicts... done.
error: failed to prepare transaction (not enough space)
:: 313.8 MB required, have 178.2 MB

the real code is in util.c, there are two hooks in sync.c and add.c
plus the error handling in pacman's sync.c