pacman: if we use /tmp as a cachedir, then tell this to libalpm, too old: $ sudo pacman -S libsidplay resolving dependencies... done. looking for inter-conflicts... done.
Targets: libsidplay-1.36.59-1

Total Package Size:   0.1 MB

Proceed with upgrade? [Y/n]

:: Retrieving packages from extra-current...
warning: no /var/cache/pacman/pkg cache exists.  creating...
warning: couldn't create package cache, using /tmp instead libsidplay-1.36.59-1-i68 [/home/ftp/pub/frugalware/frugalw] 100%    LOCAL

checking package integrity... done.
error: failed to commit transaction (could not find or read file)

new:
$ sudo pacman -S libsidplay
resolving dependencies... done.
looking for inter-conflicts... done.

Targets: libsidplay-1.36.59-1

Total Package Size:   0.1 MB

Proceed with upgrade? [Y/n]

:: Retrieving packages from extra-current...
warning: no /var/cache/pacman/pkg cache exists.  creating...
warning: couldn't create package cache, using /tmp instead libsidplay-1.36.59-1-i68 [/home/ftp/pub/frugalware/frugalw] 100%    LOCAL

checking package integrity... done.
(1/1) installing libsidplay                        [################] 100%